export const FALSE_RESPONSE = 'FALSE_RESPONSE'
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS'
export const GET_ALL_PRODUCTS_INIT = 'GET_ALL_PRODUCTS_INIT'
export const TOGGLE_DRAWER = "TOGGLE_DRAWER"
export const TOGGLE_FILTER_OPTION = "TOGGLE_FILTER_OPTION"
